server: 
  port: 0

eureka: 
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://admin:1234@localhost:8761/eureka/

security: 
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource: 
      user-info-uri: http://localhost:9999/uaa/user